#!/bin/sh
set -x
useradd -l -u ${USER_UID} -r -g 0 -d ${APP_ROOT} -s /sbin/nologin -c "${USER_NAME} application user" ${USER_NAME}
chown -R ${USER_UID}:0 ${APP_ROOT}
chmod -R g+rw ${APP_ROOT} /etc/passwd
find ${APP_ROOT} -type d -exec chmod g+x {} +
